import '@/styles/globals.css'
<<<<<<< HEAD
export const metadata = {
  title: 'Panel de Control',
  description: 'Generated by Next.js',
}
=======

>>>>>>> 77ce5e5 (Cambios 2.0)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
